# kubectl apply -f josemaria-valenzuela-41-deployment-fe.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: josemaria-valenzuela-41-deployment-fe
  namespace: josemaria-valenzuela-41-namespace-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: josemaria-valenzuela-41-deployment-fe        # Debe coincidir con las etiquetas del Service
  template:
    metadata:
      labels:
        app: josemaria-valenzuela-41-deployment-fe      # Debe coincidir con las etiquetas del Service
    spec:
      containers:
      - name: josemaria-valenzuela-41-container-fe
        image: josemariavalenzuela/gemini-huggingface-fe:1.3   # Reemplaza con tu imagen Docker Hub
        imagePullPolicy: IfNotPresent        # Evitar traer siempre la última versión si hay una actual
        envFrom:
        - secretRef:
            name: josemaria-valenzuela-41-secret-fe  # Esto cargará todos los valores como variables de entorno